version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  api:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      - SECRET_KEY=YOUR_SECRET_KEY
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydatabase
    ports:
      - "8000:8000"
    networks:
      - app_network
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  migration:
    build:
      context: .
      dockerfile: migrations/Dockerfile
    container_name: alembic_migrations
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydatabase
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
